name: example
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.2.2
  geolocator: ^10.0.0
  hive: ^2.2.3
  http: ^0.13.5
  expandable_page_view: ^1.0.17
  intl: ^0.18.0
  flutter_location_search: ^1.1.4
  geocoding: ^3.0.0
  share_plus: ^8.0.2
  screenshot: ^2.3.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/big_ben.png
    - assets/images/flag_usa.png
    - assets/images/leaf.png
    - assets/images/earth.png
    - assets/images/target.png
